name: Code Quality

on:
  workflow_call:
    inputs:
      project-directory: 
        description: 'The folder of the project'
        required: true
        type: string
jobs:
  lint-code:
    defaults:
      run:
        working-directory: ./${{ inputs.project-directory }}
        
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
      
    - name: Run ESLint
      run: yarn run eslint
    
